### ISSUE TITLE
[coc.nvim] The "perl" server crashed 4 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by Heptite** [bmeneg/coc-perl#16]
I get the following errors every time I try to edit a Perl file under Windows 11:

    [coc.nvim]: UnhandledRejection: Connection to server got closed. Server will not be restarted.
    [coc.nvim]: Error: Connection to server got closed. Server will not be restarted.
    [coc.nvim]:     at LanguageClient.handleConnectionClosed (C:\Users\Heptite\vimfiles\pack\neoclide\opt\coc.nvim\build\index.js:49812:43)
    [coc.nvim]:     at LanguageClient.handleConnectionClosed (C:\Users\Heptite\vimfiles\pack\neoclide\opt\coc.nvim\build\index.js:52116:15)
    [coc.nvim]:     at closeHandler (C:\Users\Heptite\vimfiles\pack\neoclide\opt\coc.nvim\build\index.js:49783:16)
    [coc.nvim]:     at CallbackList.invoke (C:\Users\Heptite\vimfiles\pack\neoclide\opt\coc.nvim\build\index.js:12702:35)
    [coc.nvim]:     at Emitter43.fire (C:\Users\Heptite\vimfiles\pack\neoclide\opt\coc.nvim\build\index.js:12753:34)
    [coc.nvim]:     at closeHandler (C:\Users\Heptite\vimfiles\pack\neoclide\opt\coc.nvim\build\index.js:13488:24)
    [coc.nvim]:     at CallbackList.invoke (C:\Users\Heptite\vimfiles\pack\neoclide\opt\coc.nvim\build\index.js:12702:35)
    [coc.nvim]:     at Emitter43.fire (C:\Users\Heptite\vimfiles\pack\neoclide\opt\coc.nvim\build\index.js:12753:34)
    [coc.nvim]:     at StreamMessageReader2.fireClose (C:\Users\Heptite\vimfiles\pack\neoclide\opt\coc.nvim\build\index.js:12895:27)
    [coc.nvim]:     at Socket.<anonymous> (C:\Users\Heptite\vimfiles\pack\neoclide\opt\coc.nvim\build\index.js:12977:42)
    [coc.nvim] The "perl" server crashed 4 times in the last 3 minutes. The server will not be restarted.

:CocInfo shows:

	## versions

	vim version: VIM - Vi IMproved 9.0 9000195
	node version: v18.4.0
	coc.nvim version: 0.0.82-761db753 2022-08-12 22:58:30 +0800
	coc.nvim directory: C:\Users\Heptite\vimfiles\pack\neoclide\opt\coc.nvim
	term: undefined
	platform: win32

	## Log of coc.nvim

	2022-08-12T22:08:24.286 INFO (pid:76924) [services] - registered service "languageserver.intelephense"
	2022-08-12T22:08:24.287 INFO (pid:76924) [services] - registered service "languageserver.bash"
	2022-08-12T22:08:24.378 INFO (pid:76924) [extension:coc-perl] - extension "perl" is now active
	2022-08-12T22:08:24.378 INFO (pid:76924) [extension:coc-perl] - cmd: perl args: -MPerl::LanguageServer -e Perl::LanguageServer::run -- --port 13603 --log-level 0 --log-file  --version 2.3.0
	2022-08-12T22:08:24.385 INFO (pid:76924) [plugin] - coc.nvim initialized with node: v18.4.0 after 214ms
	2022-08-12T22:08:24.394 INFO (pid:76924) [language-client-index] - Language server "perl" started with 77600
	2022-08-12T22:08:24.979 INFO (pid:76924) [language-client-index] - Language server "perl" started with 73548
	2022-08-12T22:08:25.566 INFO (pid:76924) [language-client-index] - Language server "perl" started with 49492
	2022-08-12T22:08:25.909 INFO (pid:76924) [attach] - receive notification: highlight []
	2022-08-12T22:08:26.153 INFO (pid:76924) [language-client-index] - Language server "perl" started with 74576
	2022-08-12T22:08:26.744 ERROR (pid:76924) [server] - unhandledRejection  Promise {
	  <rejected> Error: Connection to server got closed. Server will not be restarted.
	      at LanguageClient.handleConnectionClosed (C:\Users\Heptite\vimfiles\pack\neoclide\opt\coc.nvim\build\index.js:49812:43)
	      at LanguageClient.handleConnectionClosed (C:\Users\Heptite\vimfiles\pack\neoclide\opt\coc.nvim\build\index.js:52116:15)
	      at closeHandler (C:\Users\Heptite\vimfiles\pack\neoclide\opt\coc.nvim\build\index.js:49783:16)
	      at CallbackList.invoke (C:\Users\Heptite\vimfiles\pack\neoclide\opt\coc.nvim\build\index.js:12702:35)
	      at Emitter43.fire (C:\Users\Heptite\vimfiles\pack\neoclide\opt\coc.nvim\build\index.js:12753:34)
	      at closeHandler (C:\Users\Heptite\vimfiles\pack\neoclide\opt\coc.nvim\build\index.js:13488:24)
	      at CallbackList.invoke (C:\Users\Heptite\vimfiles\pack\neoclide\opt\coc.nvim\build\index.js:12702:35)
	      at Emitter43.fire (C:\Users\Heptite\vimfiles\pack\neoclide\opt\coc.nvim\build\index.js:12753:34)
	      at StreamMessageReader2.fireClose (C:\Users\Heptite\vimfiles\pack\neoclide\opt\coc.nvim\build\index.js:12895:27)
	      at Socket.<anonymous> (C:\Users\Heptite\vimfiles\pack\neoclide\opt\coc.nvim\build\index.js:12977:42)
	} Error: Connection to server got closed. Server will not be restarted.
	    at LanguageClient.handleConnectionClosed (C:\Users\Heptite\vimfiles\pack\neoclide\opt\coc.nvim\build\index.js:49812:43)
	    at LanguageClient.handleConnectionClosed (C:\Users\Heptite\vimfiles\pack\neoclide\opt\coc.nvim\build\index.js:52116:15)
	    at closeHandler (C:\Users\Heptite\vimfiles\pack\neoclide\opt\coc.nvim\build\index.js:49783:16)
	    at CallbackList.invoke (C:\Users\Heptite\vimfiles\pack\neoclide\opt\coc.nvim\build\index.js:12702:35)
	    at Emitter43.fire (C:\Users\Heptite\vimfiles\pack\neoclide\opt\coc.nvim\build\index.js:12753:34)
	    at closeHandler (C:\Users\Heptite\vimfiles\pack\neoclide\opt\coc.nvim\build\index.js:13488:24)
	    at CallbackList.invoke (C:\Users\Heptite\vimfiles\pack\neoclide\opt\coc.nvim\build\index.js:12702:35)
	    at Emitter43.fire (C:\Users\Heptite\vimfiles\pack\neoclide\opt\coc.nvim\build\index.js:12753:34)
	    at StreamMessageReader2.fireClose (C:\Users\Heptite\vimfiles\pack\neoclide\opt\coc.nvim\build\index.js:12895:27)
	    at Socket.<anonymous> (C:\Users\Heptite\vimfiles\pack\neoclide\opt\coc.nvim\build\index.js:12977:42)
	2022-08-12T22:08:40.052 INFO (pid:76924) [attach] - receive notification: showInfo []

Is this a coc.nvim issue or an issue with this language server?

**Comment by bmeneg** [comment]
Hey @Heptite, sorry for the very very long delay in replying to your issue.
But this is a language server issue, which has similar reports already: https://github.com/richterger/Perl-LanguageServer/issues/147

**Comment by bmeneg** [comment]
The language server has had several bugfixes since its last release, this problem might have been fixed already. I just asked the server maintainer for a new release so people can user the default installation process to get the newest release.
