### ISSUE TITLE
Cannot assign to read only property 'p::ls' of object '#<Object>'

### ISSUE THREAD

**Issue by Kamilcuk** [bmeneg/coc-perl#35]
Hi, so I installed `cpan Perl::LanguageServer` -> `GRICHTER/Perl-LanguageServer-2.6.1.tar.gz` on quite old machine with perl v5.28.1 on linux Fedora 29.

I installed coc-perl on nvimv0.9.1 and then I added `"perl.p::ls.enable": true` to :CocConfig.

On startup, I am not getting the following message:

```
[coc.nvim]: UnhandledRejection: Cannot assign to read only property 'p::ls' of object '#<Object>'                                                
TypeError: Cannot assign to read only property 'p::ls' of object '#<Object>'                                                                     
    at fu.extractSettingsInformation (/home/STRIKETECH/kcukrowski/.vim/plugged/coc.nvim/build/index.js:236:34391)                                
    at o (/home/STRIKETECH/kcukrowski/.vim/plugged/coc.nvim/build/index.js:236:33554)                                                            
    at fu.onDidChangeConfiguration (/home/STRIKETECH/kcukrowski/.vim/plugged/coc.nvim/build/index.js:236:33785)                                  
    at fu.register (/home/STRIKETECH/kcukrowski/.vim/plugged/coc.nvim/build/index.js:236:32929)                                                  
    at fu.initialize (/home/STRIKETECH/kcukrowski/.vim/plugged/coc.nvim/build/index.js:236:32655)                                                
    at jd.initializeFeatures (/home/STRIKETECH/kcukrowski/.vim/plugged/coc.nvim/build/index.js:241:21721)                                        
    at jd.doInitialize (/home/STRIKETECH/kcukrowski/.vim/plugged/coc.nvim/build/index.js:241:12715)                                              
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)                                                                
    at async jd._start (/home/STRIKETECH/kcukrowski/.vim/plugged/coc.nvim/build/index.js:241:7820)                                               
```

I do not reallly know what to do with it, as the errors is inside coc.nvim.

Thank you for any help!

**Comment by Twix53791** [comment]
I just had the same error msg! I spent two hours trying to found a way to install a perl LSP with coc, and at the end I arrived to make work perlnavigator instead. I am opening a new issue with a tuto about how to install...

**Comment by bmeneg** [comment]
@Kamilcuk Thanks for the report and sorry the late reply, I was somewhat offline in the past few days.
I'll check it right now and check what's going on and give you a feedback.

**Comment by Kamilcuk** [comment]
Hi, that is very amazing. No rush from my side, I was able to install perl navigator with:

```
npm install -g perlnavigator-server
```

and then enable coc-perl with:

```
           "perl.p::ls.enable": false,                                                                                                          
           "perl.enable": false,                                                                                                                
           "perl.navigator.enable": true,                                                                                                       
```

And I am happy with it.
